[mypy]
python_version = 3.8
mypy_path = $MYPY_CONFIG_FILE_DIR/packages/Python,$MYPY_CONFIG_FILE_DIR/packages/Python/lldbsuite/test/tools/lldb-dap,$MYPY_CONFIG_FILE_DIR/packages/Python/lldbsuite/test/tools/lldb-server
files = $MYPY_CONFIG_FILE_DIR/packages/Python/lldbsuite/**/*.py,$MYPY_CONFIG_FILE_DIR/test/API/tools/lldb-dap/**/*.py
warn_no_return = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
warn_unused_ignores = True
ignore_errors = True

[mypy-lldb]
disable_error_code = import-not-found,no-redef

[mypy-dap_server]
local_partial_types = True

[mypy-TestDAP_variables]
disable_error_code = index,var-annotated,attr-defined,assignment

[mypy-TestDAP_io]
ignore_errors = False
